console.log("mover");
console.log("si(hay pozo) llenar");
console.log("si(hay pila) eliminar");
console.log("mover");
console.log("si(hay pozo) llenar");
console.log("si(hay pila) eliminar");
console.log("mover");
console.log("si(hay pozo) llenar");
console.log("si(hay pila) eliminar");
console.log("mover");
console.log("si(hay pozo) llenar");
console.log("si(hay pila) eliminar");
console.log("mover");
console.log("si(hay pozo) llenar");
console.log("si(hay pila) eliminar");
console.log("mover");
console.log("si(hay pozo) llenar");
console.log("si(hay pila) eliminar");
console.log("mover");
console.log("si(hay pozo) llenar");
console.log("si(hay pila) eliminar");
